In [ ]:
import numpy as np

a = np.empty((2,2))
print (a)


[[2.80349883e-315 0.00000000e+000]
 [4.94065646e-324             nan]]


In [ ]:
b = np.ones((4,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
c = np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
d = np.zeros_like(x)
print (d)

[[0 0 0]
 [0 0 0]]


In [ ]:
e = np.ones_like(x)
print(e)

[[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
f = np.array(new_list)
print (f)

[1 2 3 4]


problem 2

In [ ]:
arr = np.arange(10, 50)
print (arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
i= np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
r = np.random.random(30)
print(r.mean())


0.4685179892984467


In [ ]:
import numpy as np
e = np.random.random((10,10))
print(e.min(), e.max())

0.004825738992484063 0.9872193723556982


In [ ]:
z = np.zeros(10)
z[4] = 1

print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = [1,2,0,0,4,0]
arr[::-1]

print (arr)


[1, 2, 0, 0, 4, 0]


In [ ]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0

print (arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
c = np.zeros((8,8))
c[1::2, ::2] = 1
c[::2, 1::2] = 1


print (c)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


problem 3

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(v+w)

[[ 6  8]
 [10 13]]
[20 22]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x-y)
print(v-w)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


print(x*5)
print(y*5)
print(v*5)
print(w*5)

[[ 5 10]
 [15 25]]
[[25 30]
 [35 40]]
[45 50]
[55 60]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x**2)
print(y**2)
print(v**2)
print(w**2)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))


219
[29 77]
[[19 22]
 [50 58]]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(np.vstack((x,y)))

print(np.concatenate((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(np.vstack((x,v)))

[[ 1  2]
 [ 3  5]
 [ 9 10]]


Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
print(A.dot(A_inv))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print(A.dot(B))
print(B.dot(A))

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

left = (A.dot(B)).T
right = B.T.dot(A.T)

print(left)
print(right)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
A = [[ 2, -3,  1],
     [ 1, -1,  2],
     [ 3,  1, -1]]

B = [-1, -3, 9]

solution = np.linalg.solve(A, B)
print(solution)



[ 2.  1. -2.]
